### ISSUE TITLE
Missing connection when trying to close it

### ISSUE THREAD

**Issue by peterbe** [mrjoes/tornadio#20]
I don't know exactly what happened for the connection to disappear. In my log files I get this:

```
[E 110606 10:44:18 iostream:237] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.6/dist-packages/tornado-1.2.1-py2.6.egg/tornado/iostream.py", line 234, in wrapper
        callback(*args)
      File "/usr/local/lib/python2.6/dist-packages/tornado-1.2.1-py2.6.egg/tornado/stack_context.py", line 156, in wrapped
        callback(*args, **kwargs)
      File "/usr/local/lib/python2.6/dist-packages/tornado-1.2.1-py2.6.egg/tornado/websocket.py", line 206, in on_connection_close
        self.on_close()
      File "/usr/local/lib/python2.6/dist-packages/TornadIO-0.0.4-py2.6.egg/tornadio/persistent.py", line 86, in on_close
        self.connection.is_closed = True
    AttributeError: 'TornadioWebSocketHandler' object has no attribute 'connection'
```

I can accept that a connection breaks every now and then. Especially with the brittle Flash stuff and, after all, WebSocket is something really new. However, this error indicates something is fundamentally wrong. It shouldn't try to do things to the connection if it's no longer there. 

Because my code is not involved in the traceback, as you can see, there's no way for me to catch the disconnection and do something like "Sorry, you're disconnected yada yada yada"

**Comment by peterbe** [comment]
I'm currently running: 
https://github.com/MrJoes/tornadio/commit/c69bd11b4fc0f94eb73bb55d59de75124b4b6e2f
on that server and I can't reproduce the error.

**Comment by mrjoes** [comment]
Thanks for bug report, fixed it. Caused by illegal/unsupported WebSocket handshake. Fix would be to silently ignore connection.

**Comment by peterbe** [comment]
"silently ignore"? Something's really wrong though. How can an instance not have that instance attribute?

**Comment by mrjoes** [comment]
I'll explain what's going on.

There's WebSocket server implementation in Tornado framework. Developers can derive from their handler class and implement three methods: open, on_message and close. 

Tornadio was expecting proper event sequence: open, then close. However, if logical WebSocket connection was not established, Tornado still calling close() without calling open().

If you check the code, Tornadio is doing some additional initialization in the open() method, which actually creates self.connection attribute.  And because open() was not called for such connections, close() was attempting to access non-existent attribute, thus crashing it.

By "silently ignore" I mean extra checks that will prevent tornadio from crashing for such clients. But if you wish, I can add debug message, not sure how it'll help.

**Comment by peterbe** [comment]
OK. So, something goes wrong during the super() call. Either way, it sounds like you've got the hang of what's going on. I'll upgrade my server when you push and report if I get any more errors like that.
