### ISSUE TITLE
session_id blank

### ISSUE THREAD

**Issue by billychasen** [mrjoes/tornadio#8]
I'm trying to swap in tornadio as a replacement to SocketTornad.io, but the session_id appears to be blank (at least in chrome websocket).

With SocketTornad.io, the handler gets a session object (self.session.id which points to the session id)

In tornadio, I see kwargs['session_id'] with the handler, but it is always blank.

Any help here would be great, thanks

**Comment by mrjoes** [comment]
Hi,

For persistent transports session_id is not being generated and used. session_id is only used on transport level to join multiple HTTP calls for polling transports into one virtual, which is not required for persistent transports.

Is there any reason why you would need it?

**Comment by billychasen** [comment]
What happens if socket.io drops the socket and reconnects it?  How do you identify that new connection as the same person (aside from doing it yourself)

I have a dictionary of sessionid => handlers for a more complex chatroom.

SocketTornad.io sends sessionid for all types of connections.

**Comment by mrjoes** [comment]
I see your point.

For each reconnect, socket.io will use new session - there's no support for graceful reconnection of persistent transports. Basically, it means that socket.io will make request without provided session_id for each connect.

Main difference between SocketTornad.IO and TornadIO - in TornadIO your connection object represents exactly one virtual connection. For each new connection you have new instance of your object. 

You don't have to map session_id to handlers, you just pass your connection object around, like you would normally do with the simple sockets.

Overall - I don't see anything bad in generating session_id for persistent transports, but in fact, it is not required (or used) because sessions are not used for persistent transports. Connection dropped? We lost client.

Hope this helps.

**Comment by billychasen** [comment]
Yes, that helps, thanks.

I engineered it to expect a sessionid, but since the connection objects are the same, there should be no harm in auto-generating an id for each (just need something hashable)

Thanks for the great work!
